language: "python"
python: "2.7"
install: "pip install -r requirements.txt"
script: "beeper build --version $TRAVIS_BUILD_NUMBER"
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "dist/clench-$TRAVIS_BUILD_NUMBER.tgz"
  skip_cleanup: true
  on:
    tags: true
