language: "python"
python: "2.7"
install: "pip install -r requirements.txt"
script: "beeper build --version $TRAVIS_BUILD_ID"
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "dist/$TRAVIS_BUILD_ID.tgz"
  skip_cleanup: true
  on:
    tags: true
