# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import henghah.album.models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio_cdn_key',
        ),
        migrations.RemoveField(
            model_name='series',
            name='cover_cdn_key',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.FileField(default='', upload_to=henghah.album.models.upload_to_audios),
        ),
        migrations.AddField(
            model_name='series',
            name='cover',
            field=models.FileField(default='', upload_to=henghah.album.models.upload_to_images),
        ),
    ]
