# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20170304_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='series',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='album.Series'),
        ),
    ]
